name: base                                                                   
channels:                                                                    
  - defaults                                                                 
dependencies:                                                                
  - pandas
  - sqlalchemy
  - scikit-learn
  - pyodbc
  - jupyterlab